ㅅtest cide

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -62,8 +62,10 @@ jobs:
             echo "TERRAFORM_BUCKET=${{ secrets.TERRAFORM_BUCKET }}" >> .env
             echo "TERRAFORM_LAMBDA_FUNCTION=${{ secrets.TERRAFORM_LAMBDA_FUNCTION }}" >> .env
             echo "ENCRYPTION_KEY=${{ secrets.ENCRYPTION_KEY }}" >> .env
+            
+            DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
+            sudo docker pull $DOCKER_USERNAME/server:$APP_VERSION || echo "Failed to pull server image"
+            sudo docker pull $DOCKER_USERNAME/client:$APP_VERSION || echo "Failed to pull client image"
 
-            docker pull ${{ secrets.DOCKER_USERNAME }}/server:$APP_VERSION 
-            docker pull ${{ secrets.DOCKER_USERNAME }}/client:$APP_VERSION 
-            docker-compose -f docker-compose.yml up -d
+            sudo docker-compose -f docker-compose.yml up -d
             docker image ls
