test cicd

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -26,15 +26,14 @@ jobs:
           docker build ./server -t ${{ secrets.DOCKER_USERNAME }}/server:$APP_VERSION 
           docker push ${{ secrets.DOCKER_USERNAME }}/server:$APP_VERSION
 
-          
       - name: List docker image
         run: docker image ls
-      
+
       # Build and push client image
       - name: Build and push client Docker image
         run: |
           docker build ./client -t ${{ secrets.DOCKER_USERNAME }}/client:$APP_VERSION 
-          docker push ${{ secrets.DOCKER_USERNAME }}/client:$APP_VERSION 
+          docker push ${{ secrets.DOCKER_USERNAME }}/client:$APP_VERSION
 
   deploy:
     needs: build-and-push
@@ -48,7 +47,7 @@ jobs:
           username: ubuntu
           key: ${{ secrets.EC2_SSH_KEY }}
           script: |
-            cd ~/kj-***
+            cd ~/kj-kloudify
             echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" > .env
             echo "DATABASE_PORT=${{ secrets.DATABASE_PORT }}" >> .env
             echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" >> .env
@@ -61,7 +60,14 @@ jobs:
             echo "TERRAFORM_BUCKET=${{ secrets.TERRAFORM_BUCKET }}" >> .env
             echo "TERRAFORM_LAMBDA_FUNCTION=${{ secrets.TERRAFORM_LAMBDA_FUNCTION }}" >> .env
             echo "ENCRYPTION_KEY=${{ secrets.ENCRYPTION_KEY }}" >> .env
-          run: |
+
+            # Start containers
             docker pull ${{ secrets.DOCKER_USERNAME }}/server:$APP_VERSION 
             docker pull ${{ secrets.DOCKER_USERNAME }}/client:$APP_VERSION 
             docker-compose -f docker-compose.yml up -d
+
+            # Wait for services to be ready (optional delay)
+            sleep 10
+
+            # Health check to verify services
+            curl -f http://localhost:80 || (echo "Health check failed!" && exit 1)
